// Catálogo canônico de reason codes. Mantém paridade com docs/data-model.md §6.
// Enviado em verification_results.reason_code e no claim `reason_code` dos tokens.

export const REASON_CODES = {
  // Decisões positivas
  THRESHOLD_SATISFIED: 'THRESHOLD_SATISFIED',
  BAND_SATISFIED: 'BAND_SATISFIED',

  // ZKP
  ZKP_PROOF_INVALID: 'ZKP_PROOF_INVALID',
  ZKP_NONCE_MISMATCH: 'ZKP_NONCE_MISMATCH',
  ZKP_PREDICATE_FAILED: 'ZKP_PREDICATE_FAILED',
  ZKP_CURVE_UNSUPPORTED: 'ZKP_CURVE_UNSUPPORTED',

  // VC / SD-JWT
  VC_SIGNATURE_INVALID: 'VC_SIGNATURE_INVALID',
  VC_ISSUER_UNTRUSTED: 'VC_ISSUER_UNTRUSTED',
  VC_CREDENTIAL_REVOKED: 'VC_CREDENTIAL_REVOKED',
  VC_EXPIRED: 'VC_EXPIRED',
  VC_NOT_YET_VALID: 'VC_NOT_YET_VALID',
  VC_SELECTIVE_DISCLOSURE_MISMATCH: 'VC_SELECTIVE_DISCLOSURE_MISMATCH',
  VC_FORMAT_UNSUPPORTED: 'VC_FORMAT_UNSUPPORTED',

  // Gateway (atestações de provedores terceiros)
  GATEWAY_ATTESTATION_INVALID: 'GATEWAY_ATTESTATION_INVALID',
  GATEWAY_PROVIDER_ERROR: 'GATEWAY_PROVIDER_ERROR',
  GATEWAY_PROVIDER_UNAVAILABLE: 'GATEWAY_PROVIDER_UNAVAILABLE',
  GATEWAY_CONFIG_MISSING: 'GATEWAY_CONFIG_MISSING',

  // Fallback
  FALLBACK_DECLARATION_ACCEPTED: 'FALLBACK_DECLARATION_ACCEPTED',
  FALLBACK_RISK_HIGH: 'FALLBACK_RISK_HIGH',
  FALLBACK_FRICTION_REQUIRED: 'FALLBACK_FRICTION_REQUIRED',

  // Erros transversais
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  SESSION_ALREADY_COMPLETED: 'SESSION_ALREADY_COMPLETED',
  POLICY_ASSURANCE_UNMET: 'POLICY_ASSURANCE_UNMET',
  POLICY_JURISDICTION_MISMATCH: 'POLICY_JURISDICTION_MISMATCH',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  INVALID_REQUEST: 'INVALID_REQUEST',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  // Boundary input rejections
  EXTERNAL_USER_REF_PII_DETECTED: 'EXTERNAL_USER_REF_PII_DETECTED',

  // Parental Consent module — promoted from RESERVED to LIVE in Round 3.
  // Emitted by `supabase/functions/parental-consent-*` edge functions and
  // by the SQL trigger that fans out parental_consent.* webhooks.
  CONSENT_GRANTED: 'CONSENT_GRANTED',
  CONSENT_DENIED: 'CONSENT_DENIED',
  CONSENT_NOT_GIVEN: 'CONSENT_NOT_GIVEN',
  CONSENT_EXPIRED: 'CONSENT_EXPIRED',
  CONSENT_REVOKED: 'CONSENT_REVOKED',
  CONSENT_PROOF_MISSING: 'CONSENT_PROOF_MISSING',
  CONSENT_GUARDIAN_NOT_VERIFIED: 'CONSENT_GUARDIAN_NOT_VERIFIED',
  CONSENT_OTP_INVALID: 'CONSENT_OTP_INVALID',
  CONSENT_OTP_EXPIRED: 'CONSENT_OTP_EXPIRED',
  CONSENT_TEXT_VERSION_MISMATCH: 'CONSENT_TEXT_VERSION_MISMATCH',
  CONSENT_RESOURCE_NOT_AUTHORIZED: 'CONSENT_RESOURCE_NOT_AUTHORIZED',
  CONSENT_NEEDS_REVIEW: 'CONSENT_NEEDS_REVIEW',
  CONSENT_BLOCKED_BY_POLICY: 'CONSENT_BLOCKED_BY_POLICY',
  CONSENT_PII_DETECTED: 'CONSENT_PII_DETECTED',

  // Safety Signals module — promoted from RESERVED to LIVE in Round 4.
  // Emitted by safety-event-ingest, safety-rule-evaluate and the SQL
  // trigger that fans out safety.* webhooks.
  SAFETY_OK: 'SAFETY_OK',
  SAFETY_RISK_FLAGGED: 'SAFETY_RISK_FLAGGED',
  SAFETY_NEEDS_REVIEW: 'SAFETY_NEEDS_REVIEW',
  SAFETY_STEP_UP_REQUIRED: 'SAFETY_STEP_UP_REQUIRED',
  SAFETY_PARENTAL_CONSENT_REQUIRED: 'SAFETY_PARENTAL_CONSENT_REQUIRED',
  SAFETY_RATE_LIMITED: 'SAFETY_RATE_LIMITED',
  SAFETY_SOFT_BLOCKED: 'SAFETY_SOFT_BLOCKED',
  SAFETY_HARD_BLOCKED: 'SAFETY_HARD_BLOCKED',
  SAFETY_BLOCKED_BY_POLICY: 'SAFETY_BLOCKED_BY_POLICY',
  SAFETY_RAW_CONTENT_REJECTED: 'SAFETY_RAW_CONTENT_REJECTED',
  SAFETY_PII_DETECTED: 'SAFETY_PII_DETECTED',
  SAFETY_UNKNOWN_EVENT_TYPE: 'SAFETY_UNKNOWN_EVENT_TYPE',
  SAFETY_PRIVACY_BUDGET_EXCEEDED: 'SAFETY_PRIVACY_BUDGET_EXCEEDED',
  SAFETY_DEVICE_BLOCKED: 'SAFETY_DEVICE_BLOCKED',
} as const;

export type ReasonCode = (typeof REASON_CODES)[keyof typeof REASON_CODES];

export const POSITIVE_REASON_CODES = new Set<ReasonCode>([
  REASON_CODES.THRESHOLD_SATISFIED,
  REASON_CODES.BAND_SATISFIED,
  REASON_CODES.FALLBACK_DECLARATION_ACCEPTED,
  REASON_CODES.CONSENT_GRANTED,
  REASON_CODES.SAFETY_OK,
]);

export function isPositive(code: ReasonCode): boolean {
  return POSITIVE_REASON_CODES.has(code);
}
