// Catálogo canônico de reason codes. Mantém paridade com docs/data-model.md §6.
// Enviado em verification_results.reason_code e no claim `reason_code` dos tokens.

export const REASON_CODES = {
  // Decisões positivas
  THRESHOLD_SATISFIED: 'THRESHOLD_SATISFIED',
  BAND_SATISFIED: 'BAND_SATISFIED',

  // ZKP
  ZKP_PROOF_INVALID: 'ZKP_PROOF_INVALID',
  ZKP_NONCE_MISMATCH: 'ZKP_NONCE_MISMATCH',
  ZKP_PREDICATE_FAILED: 'ZKP_PREDICATE_FAILED',
  ZKP_CURVE_UNSUPPORTED: 'ZKP_CURVE_UNSUPPORTED',

  // VC / SD-JWT
  VC_SIGNATURE_INVALID: 'VC_SIGNATURE_INVALID',
  VC_ISSUER_UNTRUSTED: 'VC_ISSUER_UNTRUSTED',
  VC_CREDENTIAL_REVOKED: 'VC_CREDENTIAL_REVOKED',
  VC_EXPIRED: 'VC_EXPIRED',
  VC_NOT_YET_VALID: 'VC_NOT_YET_VALID',
  VC_SELECTIVE_DISCLOSURE_MISMATCH: 'VC_SELECTIVE_DISCLOSURE_MISMATCH',
  VC_FORMAT_UNSUPPORTED: 'VC_FORMAT_UNSUPPORTED',

  // Gateway (atestações de provedores terceiros)
  GATEWAY_ATTESTATION_INVALID: 'GATEWAY_ATTESTATION_INVALID',
  GATEWAY_PROVIDER_ERROR: 'GATEWAY_PROVIDER_ERROR',
  GATEWAY_PROVIDER_UNAVAILABLE: 'GATEWAY_PROVIDER_UNAVAILABLE',
  GATEWAY_CONFIG_MISSING: 'GATEWAY_CONFIG_MISSING',

  // Fallback
  FALLBACK_DECLARATION_ACCEPTED: 'FALLBACK_DECLARATION_ACCEPTED',
  FALLBACK_RISK_HIGH: 'FALLBACK_RISK_HIGH',
  FALLBACK_FRICTION_REQUIRED: 'FALLBACK_FRICTION_REQUIRED',

  // Erros transversais
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  SESSION_ALREADY_COMPLETED: 'SESSION_ALREADY_COMPLETED',
  POLICY_ASSURANCE_UNMET: 'POLICY_ASSURANCE_UNMET',
  POLICY_JURISDICTION_MISMATCH: 'POLICY_JURISDICTION_MISMATCH',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  INVALID_REQUEST: 'INVALID_REQUEST',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  // Boundary input rejections
  EXTERNAL_USER_REF_PII_DETECTED: 'EXTERNAL_USER_REF_PII_DETECTED',

  // Webhook management (AK-P1-08)
  WEBHOOK_URL_INVALID_SCHEME: 'WEBHOOK_URL_INVALID_SCHEME',
  WEBHOOK_URL_INTERNAL_BLOCKED: 'WEBHOOK_URL_INTERNAL_BLOCKED',
  WEBHOOK_NOT_FOUND: 'WEBHOOK_NOT_FOUND',
  WEBHOOK_FORBIDDEN_TENANT: 'WEBHOOK_FORBIDDEN_TENANT',
} as const;

export type ReasonCode = (typeof REASON_CODES)[keyof typeof REASON_CODES];

export const POSITIVE_REASON_CODES = new Set<ReasonCode>([
  REASON_CODES.THRESHOLD_SATISFIED,
  REASON_CODES.BAND_SATISFIED,
  REASON_CODES.FALLBACK_DECLARATION_ACCEPTED,
]);

export function isPositive(code: ReasonCode): boolean {
  return POSITIVE_REASON_CODES.has(code);
}
