-- Migration: 030_enable_rls_audit_billing_partitions

ALTER TABLE public.audit_events_2026_04 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_events_2026_05 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_events_2026_06 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_events_2026_07 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_events_2026_08 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_events_2026_09 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_events_2026_10 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_events_2026_11 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_events_2026_12 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_events_2027_01 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_events_2027_02 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_events_2027_03 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_events_default ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.billing_events_2026_04 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.billing_events_2026_05 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.billing_events_2026_06 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.billing_events_2026_07 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.billing_events_2026_08 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.billing_events_2026_09 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.billing_events_2026_10 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.billing_events_2026_11 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.billing_events_2026_12 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.billing_events_2027_01 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.billing_events_2027_02 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.billing_events_2027_03 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.billing_events_default ENABLE ROW LEVEL SECURITY;
